// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)
<<<<<<< Updated upstream
=======

import MapController from "./map_controller"
application.register("map", MapController)

import ShowGlassCardController from "./show_glass_card_controller"
application.register("show-glass-card", ShowGlassCardController)

import ShowMapController from "./show_map_controller"
application.register("show-map", ShowMapController)
>>>>>>> Stashed changes
